### ISSUE TITLE
Flutter 2.0 nullsafety support

### ISSUE THREAD

**Issue by jailbreak2020** [leancloud/Storage-SDK-Flutter#105]
支持一下nullsafety呀，兄弟们

**Comment by weakish** [comment]
社区也有一些反馈 [24016]、[24021]

[24016]: https://forum.leancloud.cn/t/flutter-sdk-nullsafety/24016
[24021]: https://forum.leancloud.cn/t/flutter-sdk-leancloud-storage-2-0/24021

**Comment by KevinGong2013** [comment]
[Migrating to null safety](https://dart.dev/null-safety/migration-guide)

**Comment by jailbreak2020** [comment]
ping

**Comment by onerain88** [comment]
目前依赖库支持 null safety 情况：

- [ ] dio
- [x] convert: ^3.0.0
- [x] crypto: ^3.0.0
- [x] shared_preferences: ^2.0.5
- [ ] dio_http_cache: ^0.2.11
- [x] path: ^1.8.0

**Comment by chessl** [comment]
https://github.com/hurshi/dio-http-cache/pull/84#issuecomment-811637342

**Comment by onerain88** [comment]
预计下个月会计划支持（目前有优先级更高的工作）。
如有强烈需求，可以将仓库 clone 到本地，以「工程依赖」的方式引入，再自行将工程代码转化为 null safety。

**Comment by onerain88** [comment]
SDK 迁移问题统一在 [迁移 Null safety](https://github.com/leancloud/Storage-SDK-Flutter/issues/112) 中跟踪
