### ISSUE TITLE
leancloud_storage要求的版本crypto ^2.1.4太低

### ISSUE THREAD

**Issue by wish32** [leancloud/Storage-SDK-Flutter#106]
加入leancloud_storage是要求crypto ^2.1.4版本，但我的crypto已经升级到3.0.0，请问你的leancloud_storage可否升级依赖crypt到最新的版本3.0.0呢？
请问我是否有其他方法呢？由于我的项目有其他库依赖于crypt3.0.0

**Comment by onerain88** [comment]
可以 clone sdk 仓库，以「工程」依赖的方式引入 SDK
这样就可以指定 SDK 依赖的版本了

**Comment by wish32** [comment]
> 可以 clone sdk 仓库，以「工程」依赖的方式引入 SDK
> 这样就可以指定 SDK 依赖的版本了

非常感谢及时回复，请问最近有没有计划升级leancloud/Storage-SDK-Flutter的各种依赖的版本（包括crypto ）？如果使用最新的版本比较方便大家，谢谢！

**Comment by wish32** [comment]
我找到几种方法解决依赖包的版本冲突了：

https://wish32wish.blogspot.com/2021/03/flutter.html

**Comment by wish32** [comment]
> 可以clone sdk仓库，以“工程”依赖的方式发布SDK
> 这样就可以指定SDK依赖的版本了

我运行 flutter pub get 后：
Running "flutter pub get" in xxx...                         
Because leancloud_storage >=0.3.0 depends on dio_http_cache ^0.2.7 which depends on sqflite ^1.1.6+3, leancloud_storage >=0.3.0 requires sqflite ^1.1.6+3.

发现 leancloud_storage依赖的很多库都是比较旧的，例如 “sqflite 1.1.6 + 3 ” 已经是2019年7月28日发布的。

希望你们可以把依赖一起升级！谢谢！

**Comment by KevinGong2013** [comment]
> 可以 clone sdk 仓库，以「工程」依赖的方式引入 SDK
> 这样就可以指定 SDK 依赖的版本了

升级到2.0才是正确的做法吧

#105

**Comment by wish32** [comment]
> > 可以 clone sdk 仓库，以「工程」依赖的方式引入 SDK
> > 这样就可以指定 SDK 依赖的版本了
> 
> 升级到2.0才是正确的做法吧
> 
> #105

我的flutter已经升级到2.0.0，leancloud_storage运行正常，但是与其他的插件有冲突，建议升级leancloud_storage的各种依赖

**Comment by cangSDARM** [comment]
这个解决了么
为啥还用这么旧的依赖

**Comment by cangSDARM** [comment]
还有居然依赖dio……

**Comment by onerain88** [comment]
SDK 迁移问题统一在 [迁移 Null safety](https://github.com/leancloud/Storage-SDK-Flutter/issues/112) 中跟踪
