### ISSUE TITLE
LCUser.currentUser 没有保存到本地 导致每次退出应用都要重新登录

### ISSUE THREAD

**Issue by samuelhuahui** [leancloud/Storage-SDK-Flutter#14]

**Comment by onerain88** [comment]
下个版本我们将会加上这个功能，感谢关注

**Comment by samuelhuahui** [comment]
请问下个版本预计什么发呢？

**Comment by samuelhuahui** [comment]
> 请问下个版本预计什么发呢？



> 下个版本我们将会加上这个功能，感谢关注

请问下个版本预计什么时候发呢？

**Comment by onerain88** [comment]
预计本周可以发布

**Comment by onerain88** [comment]
https://github.com/leancloud/Storage-SDK-Flutter/pull/15

**Comment by onerain88** [comment]
已发布 [0.1.2](https://pub.dev/packages/leancloud_storage#-changelog-tab-)
