### ISSUE TITLE
有文档吗？

### ISSUE THREAD

**Issue by li8607** [leancloud/Storage-SDK-Flutter#17]
怎么用啊

**Comment by onerain88** [comment]
目前只有生成的 [API 文档](https://pub.dev/documentation/leancloud_storage/latest/leancloud_storage/leancloud_storage-library.html)，接口基本与其他 SDK 一致，稍后我们会把相关文档补充完整，感谢关注。

**Comment by onerain88** [comment]
也可以查看工程中的 [单元测试](https://github.com/leancloud/Storage-SDK-Flutter/tree/master/test)

**Comment by li8607** [comment]
非常好
