### ISSUE TITLE
如果得到一对多的数量？

### ISSUE THREAD

**Issue by li8607** [leancloud/Storage-SDK-Flutter#21]
您好，我最近开发过程中遇见问题，向您请教一下。
在查询Category类成功后，得到List<Category>,如何获取每个Category下有多少个Article（只得到Article数量就行）？
![image](https://user-images.githubusercontent.com/19184680/75044629-f1983f80-54fc-11ea-8025-18bbc58a4a1c.png)
![image](https://user-images.githubusercontent.com/19184680/75044712-1a203980-54fd-11ea-9d98-86727cbbfc40.png)

**Comment by onerain88** [comment]
```dart
LCQuery<Article> query = new LCQuery<Article>('Article');
// 这个 category 就是想要查找「属于的种类」
query.whereEqualTo('category', category);
int count = await query.count();
```
有点类似 https://leancloud.cn/docs/leanstorage_guide-js.html#hash1019663352

**Comment by li8607** [comment]
多谢解答。
