### ISSUE TITLE
批量删除失败。

### ISSUE THREAD

**Issue by li8607** [leancloud/Storage-SDK-Flutter#23]
您好，在进行批量删除时失败，是否在path时加上1.1?
``` String path = '/1.1/classes/${item.className}/${item.objectId}';```

![image](https://user-images.githubusercontent.com/19184680/75088897-20122b00-558e-11ea-8fa6-d9362fd37ed8.png)

![image](https://user-images.githubusercontent.com/19184680/75088900-2accc000-558e-11ea-92f0-a51b9cfe21ef.png)

**Comment by onerain88** [comment]
非常感谢您的反馈，稍后我们会修复并发布版本

**Comment by onerain88** [comment]
[0.1.4](https://pub.dev/packages/leancloud_storage/versions/0.1.4)
