### ISSUE TITLE
sdk报错了

### ISSUE THREAD

**Issue by li8607** [leancloud/Storage-SDK-Flutter#25]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'statusCode' was called on null.
E/flutter (14589): Receiver: null
E/flutter (14589): Tried calling: statusCode
E/flutter (14589): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (14589): #1      _LCHttpClient._handleError (package:leancloud_storage/internal/http/lc_http_client.dart:121:25)
E/flutter (14589): #2      _LCHttpClient.get (package:leancloud_storage/internal/http/lc_http_client.dart:48:7)
E/flutter (14589): <asynchronous suspension>
E/flutter (14589): #3      LCUser.becomeWithSessionToken (package:leancloud_storage/lc_user.dart:298:37)

**Comment by li8607** [comment]
int code = response.statusCode ~/ 100;

void _handleError(DioError e) {
    Response response = e.response;
    int code = response.statusCode ~/ 100;
    if (code == 4) {
      int code = response.data['code'];
      String message = response.data['error'];
      throw new LCException(code, message);
    }
    throw new LCException(response.statusCode, response.statusMessage);
  }

**Comment by onerain88** [comment]
statusCode 是 dio response 的属性，目前没有看出异常，这里也有 [session token 登录的单元测试](https://github.com/leancloud/Storage-SDK-Flutter/blob/ca166d372015f436026c4a1c63867d64715b8d9e/test/user_test.dart#L66)
请提供一下 SDK 版本号，以及复现步骤。

**Comment by onerain88** [comment]
这里应该是 dio 版本与 sdk 中 dio 版本不一致造成的
