### ISSUE TITLE
LCQuery.find() 方法使用问题 

### ISSUE THREAD

**Issue by wflixu** [leancloud/Storage-SDK-Flutter#26]
想查询一个对象中的所有数据，但返回类型不匹配，
代码如下：

```
LCQuery<Todo> lcq = LCQuery<Todo>('Todo');
 List<Todo> list = await lcq.find();
 list.forEach((todo){
         print(todo.desc);    
 });   
// 报错信息
//  type 'LCObject' is not a subtype of type 'Todo'

// 另外Todo 定义
class Todo extends LCObject{
  static const String ClassName = 'Todo';
  String desc;
  bool completed;
  Todo(String desc):super(Todo.ClassName){
    this.desc = desc;
    this.completed = false;
  }
  Map toJson() {
    Map map = new Map();
    map["desc"] = this.desc;
    map["completed"] = this.completed;
    return map;
  }
}

```

find 方法返回的是List<LcObject>,想显示 自定义类的属性行不通，这个该怎么写，

我看测试用例中，使用了自定义类'Hello'，其实没测试返回数据中一个Hello实例对象的属性，
如   assert(object.world!= null);

`

    test('base query', () async {
      initNorthChina();
      int limit = 2;
      LCQuery<LCObject> query = new LCQuery<LCObject>('Hello');
      query.limit(limit);
      List<LCObject> list = await query.find();
      print(list.length);
      assert(list.length > 0);
      assert(list.length == limit);

      list.forEach((object) {
        assert(object.className != null);
        assert(object.objectId != null);
        assert(object.createdAt != null);
        assert(object.updatedAt != null);
       // 这个是我自己添加的， 这样测试用例就不会通过
        assert(object.world!= null);

        print(object.className);
        print(object.objectId);
        print(object.createdAt);
        print(object.updatedAt);
        print(object['intValue']);
        print(object['boolValue']);
        print(object['stringValue']);
        print(object['world']);
      });
    });
`

不知道这个是我的使用问题还是sdk 的问题？

**Comment by onerain88** [comment]
请参考[子类化单元测试](https://github.com/leancloud/Storage-SDK-Flutter/blob/master/test/subclass_test.dart)
其中 Hello 类的 world 属性，和 World 类的 content 属性，都映射了相应的字段。
PS：请确定是否有「子类化类型的注册」。

**Comment by wflixu** [comment]
> 请参考[子类化单元测试](https://github.com/leancloud/Storage-SDK-Flutter/blob/master/test/subclass_test.dart)
> 其中 Hello 类的 world 属性，和 World 类的 content 属性，都映射了相应的字段。
> PS：请确定是否有「子类化类型的注册」。

多谢！原来这样用
