### ISSUE TITLE
只做了一个demo，debug版没问题，release版无法拉取数据

### ISSUE THREAD

**Issue by Eee721** [leancloud/Storage-SDK-Flutter#27]
如题，这是为什么呢？

**Comment by onerain88** [comment]
1. 请检查 AndroidManifest.xml 中是否有「网络访问」权限
2. 请通过
```dart
LCLogger.setLevel(LCLogger.DebugLevel);
```
查看一下请求日志

**Comment by Eee721** [comment]
已解决，是网络访问权限的问题。十分感谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: oneRain <notifications@github.com&gt;
发送时间: 2020年3月15日 17:13
收件人: leancloud/Storage-SDK-Flutter <Storage-SDK-Flutter@noreply.github.com&gt;
抄送: Eee721 <454180070@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[leancloud/Storage-SDK-Flutter] 只做了一个demo，debug版没问题，release版无法拉取数据 (#27)





  
请检查 AndroidManifest.xml 中是否有「网络访问」权限 

请通过 
 LCLogger.setLevel(LCLogger.DebugLevel);
 
查看一下请求日志

**Comment by Eee721** [comment]
还有一个问题，web版，手机浏览器，电脑浏览器，都能正常拉取数据，但ios手机浏览器却没法拉取。





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: oneRain <notifications@github.com&gt;
发送时间: 2020年3月15日 17:13
收件人: leancloud/Storage-SDK-Flutter <Storage-SDK-Flutter@noreply.github.com&gt;
抄送: Eee721 <454180070@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[leancloud/Storage-SDK-Flutter] 只做了一个demo，debug版没问题，release版无法拉取数据 (#27)





  
请检查 AndroidManifest.xml 中是否有「网络访问」权限 

请通过 
 LCLogger.setLevel(LCLogger.DebugLevel);
 
查看一下请求日志

**Comment by onerain88** [comment]
> 还有一个问题，web版，手机浏览器，电脑浏览器，都能正常拉取数据，但ios手机浏览器却没法拉取。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: oneRain <notifications@github.com&gt; 发送时间: 2020年3月15日 17:13 收件人: leancloud/Storage-SDK-Flutter <Storage-SDK-Flutter@noreply.github.com&gt; 抄送: Eee721 <454180070@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[leancloud/Storage-SDK-Flutter] 只做了一个demo，debug版没问题，release版无法拉取数据 (#27) 请检查 AndroidManifest.xml 中是否有「网络访问」权限 请通过 LCLogger.setLevel(LCLogger.DebugLevel); 查看一下请求日志 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

看一下报错信息吧。
目前主要适配的是 Android 和 iOS native，web 版本没有做太多关注。
如果有问题请再开个 issue 追踪单独的问题。
感谢关注。

**Comment by Eee721** [comment]
好的，多谢了





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: oneRain <notifications@github.com&gt;
发送时间: 2020年3月15日 21:05
收件人: leancloud/Storage-SDK-Flutter <Storage-SDK-Flutter@noreply.github.com&gt;
抄送: Eee721 <454180070@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[leancloud/Storage-SDK-Flutter] 只做了一个demo，debug版没问题，release版无法拉取数据 (#27)





  
还有一个问题，web版，手机浏览器，电脑浏览器，都能正常拉取数据，但ios手机浏览器却没法拉取。 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: oneRain <notifications@github.com&gt; 发送时间: 2020年3月15日 17:13 收件人: leancloud/Storage-SDK-Flutter <Storage-SDK-Flutter@noreply.github.com&gt; 抄送: Eee721 <454180070@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[leancloud/Storage-SDK-Flutter] 只做了一个demo，debug版没问题，release版无法拉取数据 (#27) 请检查 AndroidManifest.xml 中是否有「网络访问」权限 请通过 LCLogger.setLevel(LCLogger.DebugLevel); 查看一下请求日志 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
看一下报错信息吧。
 目前主要适配的是 Android 和 iOS native，web 版本没有做太多关注。
 如果有问题请再开个 issue 追踪单独的问题。
 感谢关注。
