### ISSUE TITLE
内部反馈

### ISSUE THREAD

**Issue by onerain88** [leancloud/Storage-SDK-Flutter#45]
- [x] 序列化和反序列化代码怎么写？[参考文档](https://leancloud.cn/docs/leanstorage_guide-java.html#hash-878532513)

- [x] 没有正则查询 query.whereMatches

//比如 java
AVQuery query = new AVQuery<>("Todo");
// "title" 不包含 "ticket"（区分大小写）
query.whereMatches("title","^((?!ticket).)*$");

- [x] 数组查询没有 whereNotContainedIn

- [x] 没有内嵌查询 MatchQuery，[参考文档](https://leancloud.cn/docs/leanstorage_guide-java.html#hash652779653)

- [ ] ~~没有 user.loginWithAuthData()，[参考文档]( https://leancloud.cn/docs/leanstorage_guide-java.html#hash774465870)~~

- [x] User 的 isAnonymous() 接口，[参考文档](https://leancloud.cn/docs/leanstorage_guide-objc.html#hash656508733)

**Comment by SXiaoXu** [comment]
- [ ] 与 `whereMatchesQuery` 对应的还有 `whereDoesNotMatchQuery`  [文档]( https://leancloud.cn/docs/leanstorage_guide-java.html#hash652779653)


- [ ] 没有`addAscendingOrder` 与 `addDescendingOrder`

**Comment by onerain88** [comment]
https://github.com/leancloud/Storage-SDK-Flutter/pull/49

**Comment by onerain88** [comment]
目前 order 相关的接口为：
orderByAscending：设置升序
orderByDescending：设置降序
addAscendingOrder：增加升序
addDescendingOrder：增加降序
请 @zapcannon87 @SXiaoXu 看下命名是否合适
