### ISSUE TITLE
ios会卡顿，android正常

### ISSUE THREAD

**Issue by liuwei11** [leancloud/Storage-SDK-Flutter#51]

**Comment by onerain88** [comment]
SDK 中耗时操作都是异步的，如返回值为 Future 类型的接口。
所以，如果使用异步 await 应该不会阻塞主线程造成卡顿。
可以先尝试排除一下是否是由于 UI 过于复杂导致的卡顿。
如果能确定为 SDK 造成的卡顿，能否提供更详细的信息。

**Comment by liuwei11** [comment]
ios虚拟机正常，真机会卡顿.android都正常

**Comment by liuwei11** [comment]
https://github.com/flutterchina/dio/issues/703  是dio的问题。

**Comment by onerain88** [comment]
看这个讨论好像和证书有关系，可以尝试在控制台绑定你们的证书试一下

**Comment by liuwei11** [comment]
用你们的证书会卡，我去阿里云申请了个证书配置上就好了

**Comment by onerain88** [comment]
咨询了一下我们 iOS 同事，提到关于 [iOS 13 证书的更新要求](https://support.apple.com/en-us/HT210176)
方便提供你在阿里云申请的证书信息吗？和我们提供的证书对比一下，看看什么问题。
