### ISSUE TITLE
支持应用内社交

### ISSUE THREAD

**Issue by zapcannon87** [leancloud/Storage-SDK-Flutter#65]
## 需求

https://leanticket.cn/tickets/23716

## 参考文档

https://leancloud.cn/docs/status_system.html
https://github.com/leancloud/java-unified-sdk/wiki/1.存储-7-Status

**Comment by onerain88** [comment]
https://leanticket.cn/tickets/23766

**Comment by onerain88** [comment]
https://github.com/leancloud/Storage-SDK-Flutter/pull/71
