### ISSUE TITLE
loginByMobilePhoneNumber和查询接口会阻塞UI线程，卡顿很明显 望解决

### ISSUE THREAD

**Issue by yew1989** [leancloud/Storage-SDK-Flutter#85]

**Comment by nnianhou-** [comment]
我这边也是这样的问题，所有查询接口都会阻塞UI线程，我用了你们的[demo](https://github.com/SXiaoXu/FlutterLeaveDemo) 也是如此，在查询数据都会卡顿
如图我是我运行你们这个demo只要是查询数据的地方都会在红色打印地方卡顿一下然后返回数据，
望解决
<img width="439" alt="WechatIMG568" src="https://user-images.githubusercontent.com/10951126/92367062-89234f80-f128-11ea-92d1-887c4118db1b.png">

**Comment by onerain88** [comment]
[初始化](https://github.com/leancloud/Storage-SDK-Flutter#initialize) 时的查询策略是如何配置的？

**Comment by nnianhou-** [comment]
初始化查询策略跟你们demo一样，参考的你们提供的那个demo
运行你们的demo情况也是一样

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: oneRain <notifications@github.com&gt;
发送时间: 2020年9月7日 16:59
收件人: leancloud/Storage-SDK-Flutter <Storage-SDK-Flutter@noreply.github.com&gt;
抄送: All in <952241861@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[leancloud/Storage-SDK-Flutter] loginByMobilePhoneNumber和查询接口会阻塞UI线程，卡顿很明显 望解决 (#85)





 
初始化 时的查询策略是如何配置的？

**Comment by nnianhou-** [comment]
> [初始化](https://github.com/leancloud/Storage-SDK-Flutter#initialize) 时的查询策略是如何配置的？

<img width="320" alt="截屏2020-09-08 上午10 58 43" src="https://user-images.githubusercontent.com/10951126/92428658-4a41d800-f1c2-11ea-90b0-94f2a005bf6c.png">

**Comment by onerain88** [comment]
我这边调查了一下，还是由于 Let's Encrypt 证书的原因（目前 Let's Encrypt 的 OCSP 服务器的部分 CDN 节点在国内少数地区存在网络连通性问题，可能会导致 iOS 应用界面卡顿。Let's Encrypt 正协同其 CDN 服务商解决这一问题。）
所以，可以先申请一个 ssl 证书，再绑定我们域名时选择手动即可。
稍后，我们也会更新一下 demo。

**Comment by Wing-Li** [comment]
现在还是这样吗？ 不论任何请求都会造成 UI 卡顿啊，这简直是致命的啊。
我是国际版的。

**Comment by onerain88** [comment]
> 现在还是这样吗？ 不论任何请求都会造成 UI 卡顿啊，这简直是致命的啊。
> 我是国际版的。
> @onerain88

有换成自己的域名和证书吗？
看下请求的证书是哪家的？请避免使用 Let's Encrypt 颁发的证书。

**Comment by Wing-Li** [comment]
> > 现在还是这样吗？ 不论任何请求都会造成 UI 卡顿啊，这简直是致命的啊。
> > 我是国际版的。
> > @onerain88
> 
> 有换成自己的域名和证书吗？
> 看下请求的证书是哪家的？请避免使用 Let's Encrypt 颁发的证书。

国家影响大吗？
阿里云申请的是在杭州。
云引擎里面将SSL改成手动之后，还需要做什么别的事情吗？

**Comment by onerain88** [comment]
首先确认一下是 iOS 系统，并且使用的是 Let's Encrypt 颁发的证书，导致卡顿的问题。
然后绑定自己的域名 + 自己的证书（非 Let's Encrypt）。
最后，初始话 SDK 时修改为绑定的自己的域名。
（在控制台->设置->绑定域名下面有蓝字说明）

**Comment by Wing-Li** [comment]
每次我把 域名 加到 初始化的 server 字段里，LeanCloud 就不能访问了。
在域名前面或后面还要加什么 前缀 后缀吗？

**Comment by Wing-Li** [comment]
![image](https://user-images.githubusercontent.com/12133489/103191724-fc87e180-4910-11eb-8c6b-dcf4c96eb390.png)

**Comment by onerain88** [comment]
我刚在后台看这个域名是绑定在「云引擎」上的，而初始化时填写的 server 应该是「API 域名」。
但国际节点目前暂时不支持绑定 API 域名，我们讨论下如何解决 ocsp 的问题。

**Comment by Wing-Li** [comment]
我发现，初始化时加上 server ，就不卡了。
server 填的是 Request api 的那个。

> xxxxxxe6.api.lncldglobal.com

**Comment by onerain88** [comment]
我们重签了 *.api.lncldglobal.com 的证书，目前证书的 ocsp 地址（http://r3.o.lencr.org/）国内访问是正常的，可以再试试。
